name: Flask API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Flask and pytest
        run: |
          python -m pip install --upgrade pip
          pip install Flask pytest

      - name: Run Flask API tests
        run: |
          cd Exo2
          python -m pytest
